"""The LifeSci-PaperRecon approved paper set.

These three papers were selected by hand (approved plan, "Phase 0 results") to
give the pilot mixed paper-type coverage rather than three samples of the same
shape. The name is `APPROVED_PAPERS` rather than `PILOT_PAPERS` because the
pilot is over: as the corpus scales, this is the human-approved list that
`core.screen` proposes candidates *for* and never writes to, and that the
construction gate's `provenance-mismatch` check treats as authoritative. That mix is a deliberate human decision, so the build **never
substitutes a paper**: if re-verification finds that a paper no longer
qualifies — the license changed, the submission is PDF-only, the linked
repository is gone — the build stops and reports, and a human re-decides.

Every field below is an *expectation* the construction agent must re-verify
against the live arXiv abstract page, not a trusted fact. The validation gate
(:mod:`paperbench_harbor.construction.core.validate`) cross-checks the agent's
recorded `provenance.json` against these expectations and fails the paper on any
mismatch.

:class:`PaperSpec` and :data:`ACCEPTED_LICENSES` are re-exported from
:mod:`paperbench_harbor.construction.core.spec`, where they moved when
PaperSmith was split into a core and per-domain plugins; neither ever carried a
biology-specific field.
"""

from __future__ import annotations

from paperbench_harbor.construction.core.spec import ACCEPTED_LICENSES, PaperSpec

__all__ = ["ACCEPTED_LICENSES", "APPROVED_BY_ID", "APPROVED_PAPERS", "PaperSpec"]

#: Papers a human has approved for construction. `core.screen` proposes
#: candidates for this list; only a human ever adds to it.
APPROVED_PAPERS: tuple[PaperSpec, ...] = (
    PaperSpec(
        paper_id="paper_1",
        arxiv_id="2606.27607",
        paper_type="computational",
        code_repo="https://github.com/beagle-dev/beagle-lib",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.PE",
        note="BEAGLE 4.1 — phylogenetics library / tool paper.",
    ),
    PaperSpec(
        paper_id="paper_2",
        arxiv_id="2503.19375",
        paper_type="computational",
        code_repo=(
            "https://github.com/DominicDevlin/"
            "Stem-cell-differentiation-underpins-reproducible-morphogenesis"
        ),
        expected_license="CC BY 4.0",
        expected_version="v2",
        expected_category="q-bio.CB",
        note=(
            "Cell differentiation underpins reproducible morphogenesis — "
            "hypothesis-driven simulation study."
        ),
    ),
    PaperSpec(
        paper_id="paper_3",
        arxiv_id="2601.02265",
        paper_type="experimental",
        code_repo="https://github.com/mdsamad001/Drug_Release_Dynamics_Prediction",
        expected_license="CC BY-SA 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="Explainable ML for drug-release prediction — applied empirical study.",
    ),
    # --- Phase 4 scale-up: 35 papers promoted from screening (2026-08-31) ---
    PaperSpec(
        paper_id="paper_4",
        arxiv_id="2608.25194",
        paper_type="computational",
        code_repo="https://github.com/ajogalekar/rna-at-most-two-short-helices",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="RNA inverse folding with at-most-two-short-helices. (Cross-listed q-bio.BM.)",
    ),
    PaperSpec(
        paper_id="paper_5",
        arxiv_id="2608.18982",
        paper_type="experimental",
        code_repo="https://github.com/blazejba/monroe",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="Bioassay activity prediction with molecular foundation models. (Cross-listed q-bio.BM.)",
    ),
    PaperSpec(
        paper_id="paper_6",
        arxiv_id="2607.07866",
        paper_type="computational",
        code_repo="https://github.com/WSobo/UMA-Inverse",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="UMA-Inverse — ligand-conditioned protein inverse folding.",
    ),
    PaperSpec(
        paper_id="paper_7",
        arxiv_id="2607.07352",
        paper_type="computational",
        code_repo="https://github.com/bio-phys/BRMSD",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="BRMSD — Boltzmann-reweighted RMSD for molecular dynamics.",
    ),
    PaperSpec(
        paper_id="paper_8",
        arxiv_id="2607.04134",
        paper_type="computational",
        code_repo="https://github.com/HPuntu/DynaMode",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="DynaMode — Fourier-based generative protein dynamics.",
    ),
    PaperSpec(
        paper_id="paper_9",
        arxiv_id="2606.11382",
        paper_type="computational",
        code_repo="https://github.com/eemokey/glacier",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="GLACIER — multi-modal molecular property prediction. (Cross-listed q-bio.BM.)",
    ),
    PaperSpec(
        paper_id="paper_10",
        arxiv_id="2606.04566",
        paper_type="computational",
        code_repo="https://github.com/clami66/AF_cache",
        expected_license="CC BY-SA 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="AlphaFold MSA cache for protein-protein interaction prediction.",
    ),
    PaperSpec(
        paper_id="paper_11",
        arxiv_id="2606.02462",
        paper_type="computational",
        code_repo="https://github.com/Jiarui0923/APL",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="APL — antigen processing-aware epitope prediction.",
    ),
    PaperSpec(
        paper_id="paper_12",
        arxiv_id="2605.31498",
        paper_type="computational",
        code_repo="https://github.com/countrsignal/sita",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="SITA — iterative finetuning of diffusion models for molecular Boltzmann sampling. (Cross-listed q-bio.BM.)",
    ),
    PaperSpec(
        paper_id="paper_13",
        arxiv_id="2606.07567",
        paper_type="computational",
        code_repo="https://github.com/smiles724/SurfDesign",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="SurfDesign — surface-conditioned protein design.",
    ),
    PaperSpec(
        paper_id="paper_14",
        arxiv_id="2605.11764",
        paper_type="computational",
        code_repo="https://github.com/ThorKlm/PROTAC-Bench",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="PROTAC-Bench — evaluation science for targeted protein degradation. (Cross-listed q-bio.BM.)",
    ),
    PaperSpec(
        paper_id="paper_15",
        arxiv_id="2605.23960",
        paper_type="computational",
        code_repo="https://github.com/AI-HPC-Research-Team/ProtDiS",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.BM",
        note="ProtDiS — disentangled protein representations.",
    ),
    PaperSpec(
        paper_id="paper_16",
        arxiv_id="2605.08659",
        paper_type="computational",
        code_repo="https://github.com/IDEA-XL/SGRPO",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.CE",
        note="SGRPO — diverse biomolecular generation via group relative policy optimization. (Cross-listed q-bio.BM.)",
    ),
    PaperSpec(
        paper_id="paper_17",
        arxiv_id="2608.20184",
        paper_type="computational",
        code_repo="https://github.com/PEtab-dev/petab_sciml",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="PEtab SciML — reproducible SciML training for ODE-ML hybrid models.",
    ),
    PaperSpec(
        paper_id="paper_18",
        arxiv_id="2608.17571",
        paper_type="experimental",
        code_repo="https://github.com/Ruizhe-wang/DMT-Dens",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="DMT-Dens — density-preserving embeddings for single-cell data.",
    ),
    PaperSpec(
        paper_id="paper_19",
        arxiv_id="2608.16951",
        paper_type="experimental",
        code_repo="https://github.com/travis42/little-scientist-dale",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="Little Scientist DALE — LLM-based automated algorithm design.",
    ),
    PaperSpec(
        paper_id="paper_20",
        arxiv_id="2608.07344",
        paper_type="computational",
        code_repo="https://github.com/CoMuNeLab/MuxVizPy",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="MuxVizPy — multilayer biological network analysis.",
    ),
    PaperSpec(
        paper_id="paper_21",
        arxiv_id="2608.07590",
        paper_type="computational",
        code_repo="https://github.com/TiagoCortinhal/fgr-geometry",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="stat.AP",
        note="Fetal growth representation geometry — information-geometric imputation. (Cross-listed q-bio.QM.)",
    ),
    PaperSpec(
        paper_id="paper_22",
        arxiv_id="2608.05196",
        paper_type="experimental",
        code_repo="https://github.com/duckyquang/MS-MLB",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="MS-MLB — multiple-sclerosis blood RNA classifier. (Cross-listed q-bio.QM.)",
    ),
    PaperSpec(
        paper_id="paper_23",
        arxiv_id="2608.02796",
        paper_type="experimental",
        code_repo="https://github.com/Bluesman79/REDE-transcriptomic-reproducibility",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="REDE — transcriptomic reproducibility evaluation.",
    ),
    PaperSpec(
        paper_id="paper_24",
        arxiv_id="2608.02684",
        paper_type="computational",
        code_repo="https://github.com/PKU-Alignment/SPIKE-Bench",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="SPIKE-Bench — protein-level biosecurity evaluation for LLMs.",
    ),
    PaperSpec(
        paper_id="paper_25",
        arxiv_id="2607.19600",
        paper_type="experimental",
        code_repo="https://github.com/mpff/dnn-shapes",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="stat.ME",
        note="Deep shape regression for open planar curves in neuroimaging. (Cross-listed q-bio.QM.)",
    ),
    PaperSpec(
        paper_id="paper_26",
        arxiv_id="2608.00405",
        paper_type="experimental",
        code_repo="https://github.com/NozomiMizore/MSGR",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.AI",
        note="MSGR — spatial gene expression from histopathology via multi-scale graph reasoning. (Cross-listed q-bio.GN.)",
    ),
    PaperSpec(
        paper_id="paper_27",
        arxiv_id="2606.18672",
        paper_type="experimental",
        code_repo="https://github.com/W-RMSL/scGTN",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="scGTN — single-cell RNA-seq clustering via graph transformer. (Cross-listed q-bio.GN.)",
    ),
    PaperSpec(
        paper_id="paper_28",
        arxiv_id="2606.15357",
        paper_type="experimental",
        code_repo="https://github.com/lh3/minibwa",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="minibwa — fast short-read mapper replacing BWA-MEM.",
    ),
    PaperSpec(
        paper_id="paper_29",
        arxiv_id="2606.08147",
        paper_type="computational",
        code_repo="https://github.com/DuanYi516/R3LM",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="R3LM — regulatory-element language model for cis-regulatory activity prediction.",
    ),
    PaperSpec(
        paper_id="paper_30",
        arxiv_id="2606.06117",
        paper_type="computational",
        code_repo="https://github.com/MAHI-Group/pVR",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.QM",
        note="pVR — p-adic topological ML for alignment-free genomic classification. (Cross-listed q-bio.GN.)",
    ),
    PaperSpec(
        paper_id="paper_31",
        arxiv_id="2605.24520",
        paper_type="computational",
        code_repo="https://github.com/MuhammadMuneeb007/CAGI7_Annotate_All_Missense",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="AnnotateMissense — missense variant annotation and pathogenicity benchmarking.",
    ),
    PaperSpec(
        paper_id="paper_32",
        arxiv_id="2605.18587",
        paper_type="experimental",
        code_repo="https://github.com/AI4Science-WestlakeU/PACE",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="PACE — physics-aligned trajectory inference from single-cell snapshots.",
    ),
    PaperSpec(
        paper_id="paper_33",
        arxiv_id="2605.02954",
        paper_type="computational",
        code_repo="https://github.com/MuhammadMuneeb007/EFGPP",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="EFGPP — ensemble framework for genotype-to-phenotype prediction.",
    ),
    PaperSpec(
        paper_id="paper_34",
        arxiv_id="2605.01378",
        paper_type="computational",
        code_repo="https://github.com/MuhammadMuneeb007/PhenotypeToGeneDownloaderR",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="PhenotypeToGeneDownloaderR — phenotype-to-gene evidence aggregation.",
    ),
    PaperSpec(
        paper_id="paper_35",
        arxiv_id="2605.00074",
        paper_type="computational",
        code_repo="https://github.com/najmulhasan-code/crc-screen",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="q-bio.GN",
        note="CRC-Screen — DNA synthesis screening under conformal risk control.",
    ),
    PaperSpec(
        paper_id="paper_36",
        arxiv_id="2606.23957",
        paper_type="computational",
        code_repo="https://github.com/MohammedNagdi/Attended-Koopman",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.LG",
        note="Attended Koopman — attention-augmented Koopman operators for biological networks. (Cross-listed q-bio.MN.)",
    ),
    PaperSpec(
        paper_id="paper_37",
        arxiv_id="2603.16562",
        paper_type="experimental",
        code_repo="https://github.com/bozeklab/Cell-Fate-Prediction",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="cs.CV",
        note="Cell fate prediction from live-cell imaging via deep learning. (Cross-listed q-bio.CB.)",
    ),
    PaperSpec(
        paper_id="paper_38",
        arxiv_id="2608.12072",
        paper_type="computational",
        code_repo="https://github.com/geosop/LEVEL-IIA",
        expected_license="CC BY 4.0",
        expected_version="v1",
        expected_category="stat.ME",
        note="LEVEL-IIA — design-based inference framework for anticipatory EEG. (Cross-listed q-bio.NC.)",
    ),
)

APPROVED_BY_ID = {spec.paper_id: spec for spec in APPROVED_PAPERS}
